### ISSUE TITLE
Support HC 12.4.1

### ISSUE THREAD

**Issue by marekbomber** [benmccallum/fairybread#72]
**Error message**
`Method not found: 'HotChocolate.Types.IFieldCollection1<HotChocolate.Types.IInputField> HotChocolate.Types.IOutputField.get_Arguments()'.`

**Error stack trace**
`at FairyBread.ValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at FairyBread.ValidationMiddleware.InvokeAsync(IMiddlewareContext context)\r\n   at lambda_method1014(Closure , IMiddlewareContext , ValidationMiddleware )\r\n   at HotChocolate.Resolvers.FieldClassMiddlewareFactory.<>c__DisplayClass5_01.<CreateDelegate>b__1(IMiddlewareContext context)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)\r\n   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)`

**Versions:**
 - FairyBread: 8.0.0
 - HotChocolate: 12.4.1
 - FluentValidation: 10.3.6

**Comment by brian-tygotech** [comment]
The problem is that the Hot Chocolate `IFieldCollection` has changed its type from `IReadOnlyList` to `IReadOnlyCollection` so in `ValidationMiddleware.InvokeAsync` the enumeration of the fields fails to bind.

Since `IReadOnlyList` implements `IReadOnlyCollection` I think alll you need to do is rebuild the project and that should be a non-breaking fix that would allow old and new versions of HC to work.

**Comment by vhatsura** [comment]
@brian-tygotech, I think the reason is slightly different. `Arguments` property was moved from `IOutputField` interface to.`IOutputFieldInfo`. IL has information on which interface method should be called, and for this reason, it cannot find the `get_Arguments` method on the `IOutputField` interface. So, it's a binary breaking change, and rebuilding source code will not be enough. HotChocolate dependency should be updated first and then rebuild should help

**Comment by brian-tygotech** [comment]
@vhatsura yes, you're right, you need to build against the latest version.

@benmccallum thanks, much appreciated.

**Comment by marekbomber** [comment]
> Thanks everyone! Should be a 9.0.0-rc.1 release of FairyBread up in a few minutes that's compiled against v12.4.0 of HC. Let me know if that fixes this issue.
> 
> Note: Released as an RC just in case this breaking change is rolled out of HC, but will a full v9 in a couple of days assuming we've gotta deal with it.

Thanks!
Everything works very well in version 9.0.0-rc.1!
