### ISSUE TITLE
Q: Throwing custom exceptions

### ISSUE THREAD

**Issue by mrodrigues95** [benmccallum/fairybread#75]
HC 12.4 introduced new ways for [error handling](https://chillicream.com/docs/hotchocolate/defining-a-schema/mutations/#errors) which involve creating your own exceptions and throwing them manually.

Is there any way to throw custom exceptions within the validator if validation fails so that they are caught in the middleware and mapped to the appropriate payload? Currently, when validation fails it will usually result in a `500` response and I was curious if there is any way to take advantage of the new HC error handling.

I understand you can make your own `IValidationErrorsHandler` but I'm not exactly sure how that would look with this implementation.

**Comment by benmccallum** [comment]
I think a custom `IValidationErrorsHandler` would be too generic, as I imagine you want to throw a context-sensitive exception that turns into an error on the payload, from inside an AbstractValidator, like `EmailAlreadyTaken`.

I'm honestly not sure what happens when you throw within an abstract validator. Potentially FluentValidation handles it and wraps that in a validation error. 

Do you wanna give it a try and report back? 

If FV lets the exception bubble up, then I guess it'd bubble through the FairyBread middleware and up into the HC middleware and get captured by the new mutation convention and error handling... but I'm not sure if it'd be a nice pattern to be putting throws in a validator. 

Perhaps HC has a mechanism like `context.ReportError` for reporting an error that should be considered a payload error, but you still need something concrete for it to create the error type and build the union.

I think the way I currently see all this is that ideally your FE should be doing client-side validation and hitting errors from FairyBread validation should be an unusual case / safe-guard. If you do have some domain specific errors you want to expose in the payload, that logic should be part of the mutation resolver, rather than an AbstractValidator.

**Comment by mrodrigues95** [comment]
> I'm honestly not sure what happens when you throw within an abstract validator. Potentially FluentValidation handles it and wraps that in a validation error.

Yeah, I've tried doing this and it gets handled like any other validation error. It does not bubble up into the payload.

> I think the way I currently see all this is that ideally your FE should be doing client-side validation and hitting errors from FairyBread validation should be an unusual case / safe-guard.

This is a good way of looking at it, honestly. If the client is getting validation errors triggered from FairyBread, then that signalizes a deeper problem where the client validation is not in sync with the server.

With that being said, the current implementation is perfectly fine then. I'll use the new HC error handling specifically for domain level errors.

Appreciate that response.
